require "ruby_parser"

require "ahiru/version"

require "ahiru/issue"
require "ahiru/world"
require "ahiru/source_file"
require "ahiru/tool"
require "ahiru/duck"
require "ahiru/broken_duck"
require "ahiru/union"
require "ahiru/callable"
require "ahiru/method"
require "ahiru/block"

require "ahiru/scope"
require "ahiru/main_scope"
require "ahiru/file_scope"
require "ahiru/child_scope"
require "ahiru/block_scope"
require "ahiru/method_scope"
require "ahiru/module_scope"
require "ahiru/class_scope"
require "ahiru/block_definition_resolver"
require "ahiru/method_definition_resolver"
require "ahiru/class_definition_resolver"

require "ahiru/definitions"